/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wwheeler' at '1/22/16 10:02 AM' with Gradle 2.10
 *
 * @author wwheeler, @date 1/22/16 10:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
